### ISSUE TITLE
evil-magit breaks evil-want-C-u-scroll

### ISSUE THREAD

**Issue by fantasticsid** [emacs-evil/evil-magit#27]
I set ```evil-want-C-u-scroll``` to true so that I can scroll up exactly like in vim, installing evil-magit breaks it and I couldn't scroll back with C-u any more.

evil version: 1.2.12
evil-magit version: 20161130.847

**Comment by justbur** [comment]
I need more information. Are you saying it breaks it everywhere? In all magit buffers? In particular buffers?

**Comment by NicholasTD07** [comment]
@justbur I also have the same problem and I found out it's because of the evil-magit package. If I remove the package, without any other change to my configurations, C-u works.

The C-u does not work in evil-normal or evil-visual mode nor does it work in magit buffers.

Emacs: 25.2.1
evil: 20170712.2350
evil-magit: 20170613.510

**Comment by justbur** [comment]
It still doesn't make sense to me. I'll need a config that I can use from `emacs -Q` to reproduce this.

**Comment by NicholasTD07** [comment]
@justbur Here's my emacs configuration. https://github.com/NicholasTD07/dotfiles/tree/master/.emacs.d

Get the `init.el` file and also the `lisp` directory. When you load the `init.el` file it should bootstrap the package manager (I use `use-package`) and download and set up all the packages for you. This should give you an exact copy of what I have.

I have removed `evil-magit` from my configs tho. To reproduce the issue, you can  add this somewhere in my configurations files.
```elisp
(use-package evil-magit
  :config (evil-magit-init))
```

It should help you reproduce the issue.

Let me know if I can help you in anyway :)


PS.

Or, you can clone my `dotfile` repo and checkout at this commit https://github.com/NicholasTD07/dotfiles/commit/c4ac9bbeab14146874be95e1664d2fce6ef101ae and load the `init.el` file.
The `evil-magit` configuration is in that commit. I removed it in the one after it.

**Comment by justbur** [comment]
`evil-want-C-u-scroll` needs to be set before evil is loaded. evil-magit loads evil, and it appears you are loading evil-magit before evil which will cause the problem. This isn't an evil-magit bug.

**Comment by NicholasTD07** [comment]
@justbur Thanks. After adjusting my configs, `C-u` works!

Sorry for the falsely bug reporting. Emacs is still quite new to me and there are so many things I am still trying to understand. 

Thanks.

**Comment by justbur** [comment]
No problem

**Comment by fantasticsid** [comment]
yeah, works for me as well now. Thanks!
