### ISSUE TITLE
with evil-magit-want-horizontal-movement C-l to Change Log not obvious

### ISSUE THREAD

**Issue by bandresen** [emacs-evil/evil-magit#31]
Hey,

I found it within the code but when `evil-magit-want-horizontal-movement` is enabled then both =Logging= and =Change Logs= show as `L`.

Not a big deal but worth noting. :-)

Best regards,
benny

**Comment by justbur** [comment]
Thanks, try it after f851e5896fa90ae94dfde3d2a7554b4d5f9e665c
