### ISSUE TITLE
request magit-repolist-mode support

### ISSUE THREAD

**Issue by ambihelical** [emacs-evil/evil-magit#35]
Currently this mode (via magit-list-repositories) doesn't work very well with evil, a few important bindings such as RET are hidden by evil.  For now I have it in the 'evil-emacs-state-modes list, but it would be nice if it was supported in evil-magit.

**Comment by justbur** [comment]
That looks like a new command. I can add support for it. I think I would do this in this case
```elisp
(evil-set-initial-state 'magit-repolist-mode 'motion)
(evil-define-key 'motion magit-repolist-mode-map
  (kbd "RET") 'magit-repolist-status
  (kbd "gr")  'magit-list-repositories)
```
Is that what you would expect?

**Comment by ambihelical** [comment]
That seems reasonable, assuming motion mode allows "q" to quit the mode.

**Comment by justbur** [comment]
It does. I just pushed that change. Feel free to repoen this issue if you notice something odd.
