### ISSUE TITLE
magit compatibility: Error the keymap magit-blame-mode-map is not bound

### ISSUE THREAD

**Issue by kommen** [emacs-evil/evil-magit#43]
The mode map was renamed to `magit-blame-read-only-mode-map` in https://github.com/magit/magit/commit/6d7127d6e37f48d7256c954cf36f98a82d6a23f5.

**Comment by everedifice** [comment]
same problem here

**Comment by vxid** [comment]
Same issue happened right after updating this morning. My guess is that this issue is related to the magit-blame-related commits of yesterday on the magit repo.

**Comment by justbur** [comment]
Fixed in #41
