### ISSUE TITLE
magit-blame somehow nullifies evil-state

### ISSUE THREAD

**Issue by amosbird** [emacs-evil/evil-magit#44]
after entering `magit-blame` state, `(evil-state-property evil-state :name)` returns nil. All evil bindings vanish. I've tried
```
(add-hook 'magit-blame-mode-hook #'evil-normal-state)
(add-hook 'magit-blame-read-only-mode-hook #'evil-normal-state)
```

and

```
(evil-set-initial-state 'magit-blame-mode 'normal)
```

neither works

**Comment by justbur** [comment]
First, `magit-blame-mode` is a minor mode, not a state. If you want to know the current evil state you just need to do `C-h v evil-state RET`. 

Second, I can't reproduce this. I don't have any issues with the state changing after `M-x magit-blame`. I'll need more information.

**Comment by amosbird** [comment]
Yeah, it's not reproducible in `emacs -Q`.
