### ISSUE TITLE
All file buffers are starting in evil-motion-state

### ISSUE THREAD

**Issue by awalker4** [emacs-evil/evil-magit#46]
This started happening after a recent package update, and I believe it's because Magit has now [globally enabled magit-file-mode](https://github.com/magit/magit/commit/0ec28b97b587a2a75f7f729a45e173d69bf5441b) which I see is included in evil-magit-default-to-evil-magit-state-modes.  Not sure if other people are seeing this issue, so let me know if you need any debug info.

**Comment by justbur** [comment]
Thanks. Changing the evil-state in that mode is a mistake. Should be fixed with fe418dc
