### ISSUE TITLE
[feature request] support for magic-todos

### ISSUE THREAD

**Issue by casouri** [emacs-evil/evil-magit#50]
There is this new package [magit-todos](https://github.com/alphapapa/magit-todos).

It binds `jT` which should be `gT` in the evil world.

**Comment by justbur** [comment]
See https://github.com/emacs-evil/evil-collection/pull/177

**Comment by justbur** [comment]
I will probably merge evil-magit into evil-collection anyway

**Comment by casouri** [comment]
Cool
