### ISSUE TITLE
Moving to parent section

### ISSUE THREAD

**Issue by DanielRichtmann** [emacs-evil/evil-magit#56]
Hi,

I just came across an inconsistency in the mapping of the keys (at least IMO):

While `evil-magit` binds `gk` and `gj` to move to the the next/previous sibling in the status window, there are no bindings for `gh` and `gl`.

Looking at, e.g., the evil bindings for `org-mode`, `gh` and `gl` get bound to move to the parent/child of the current heading.

IMO `gl` doesn't make a lot of sense here but I think that `gh` might come in handy, so perhaps it should be bound, too.

Out of the current functionality in `magit`, the candidate for this is probably `magit-section-up`, which is what I currently bind in my config.

Let me know what you think. I can PR if you want me to.

**Comment by justbur** [comment]
I think it makes sense to me. Generally, unless there's a conflict I'm happy to try a binding out. If you want to submit a PR, I'd be happy to review it.
