### ISSUE TITLE
Support for GPG signing

### ISSUE THREAD

**Issue by lucianonooijen** [emacs-evil/evil-magit#66]
It seems like currently there is no built in support for GPG signing commits in the commit screen (`SPC - g - s`, `S - y`, `c`). 

This would be a great feature to add

**Comment by justbur** [comment]
You’re proposing keybindings for the commit buffer? What are the corresponding bindings in magic?

**Comment by lucianonooijen** [comment]
I'm not familiar with Magit bindings as I'm new to Emacs/Spacemacs, although I found [this reference to it in the source code](https://github.com/magit/magit/blob/039feb027023503d1aa9db845f80dae986d8130b/lisp/magit-commit.el#L115). Due to my very limited skills with (Emacs-)Lips, I'm not sure what the added functionality should be.

**Comment by justbur** [comment]
Magit handles this in the commit popup, not in the commit buffer. See for example https://emacs.stackexchange.com/questions/18514/how-to-automatically-sign-commits-with-magit/18524
