### ISSUE TITLE
In vanilla Magit I can use C-u s to do a "git add -N", can I do this with evil-magit?

### ISSUE THREAD

**Issue by brainlessdeveloper** [emacs-evil/evil-magit#67]
I want to use `git add -N` with Magit.

```
       -N, --intent-to-add
           Record only the fact that the path will be added later.
           An entry for the path is placed in the index with no
           content. This is useful for, among other things, showing
           the unstaged content of such files with git diff and
           committing them with git commit -a.
```

This behavior is supported by vanilla Magit by using `C-u s`, it was implemented in [this PR](https://github.com/magit/magit/pull/2638).

How can I do this with evil-magit?

P.S. Thank you for this package :)

**Comment by justbur** [comment]
I'm not sure how this would be handled in evil-magit. Do you have a key binding in mind?

**Comment by brainlessdeveloper** [comment]
I was thinking it could be the default `s` action when adding new files. A subsequent `s` could actually stage the changes?

**Comment by justbur** [comment]
It’s not a bad suggestion but I’d rather stay close to the way Magit works. I think that’s a suggestion that could be made on the Magit side.

**Comment by brainlessdeveloper** [comment]
What about just `n`? for `git add -N` or `i<n>tent`?

**Comment by justbur** [comment]
That’s reserved for searching.

**Comment by brainlessdeveloper** [comment]
How about capital `I` (i) for `<i>ntent`? Currently I get an "ignore" dialog but that also works with lowercase `i`. We could:

- Keep lowercase `i` for the ignore dialog.
- Use uppercase `I` for `git add -N`.

**Comment by justbur** [comment]
ok, worth a try. I added it in 91e5dfb

**Comment by brainlessdeveloper** [comment]
Cool! Thanks!

**Comment by brainlessdeveloper** [comment]
Working great on the new release btw.
