### ISSUE TITLE
Bury buffer with 'q'?

### ISSUE THREAD

**Issue by ianpan870102** [emacs-evil/evil-magit#78]
Coming from default magit, I've been used to burying the buffer with pressing 'q'. However, in evil-magit, the 'q' key sometimes doesn't bury the window itself, leaving the magit buffer gone but some other open buffer taking its place.
I realized that evil-magit uses <esc> to achieve burying both the buffer and the window. Is there a way to bind this to 'q'?

**Comment by justbur** [comment]
Good catch. Thanks. Should be fixed with 7223dca
