### ISSUE TITLE
magit-section don't work with evil visual-state

### ISSUE THREAD

**Issue by mohkale** [emacs-evil/evil-magit#79]
Not sure whether this is an evil-magit issue or a magit issue, but if on `magit-status` you start a visual selection (to choose some hunks to stage) and then try running any of the section commands such as `magit-section-forward-sibling` or `magit-section-forward` they don't do anything. If I exit visual state, they work fine but within visual state they don't.

I'm on `GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29` and using `Evil version 1.13.0`.

**Comment by justbur** [comment]
Thanks. This should be fixed with 515cb144709334aa7e1543f5618a92b549801789. Let me know if you find anymore issues with visual state like this.
