### ISSUE TITLE
respect evil-toggle-key

### ISSUE THREAD

**Issue by mohkale** [emacs-evil/evil-magit#82]
`evil-toggle-key` defaults to `C-z`, but `evil-magit` hardcodes `C-z` instead of using the value of `evil-toggle-key`. Personally I've remapped `C-z` to something else so I'd prefer if `evil-magit` didn't reintroduce it.

See [here](https://github.com/emacs-evil/evil-magit/blob/master/evil-magit.el#L323).

**Comment by justbur** [comment]
Sounds good to me. Should be fixed now
