### ISSUE TITLE
evil-magit not available on MELPA

### ISSUE THREAD

**Issue by janmasrovira** [emacs-evil/evil-magit#90]
The melpa page for evil-magit (https://melpa.org/#/evil-magit) says "Package not found: evil-magit".

Consequently, when I try: `M-x package-install RET evil-magit`, it does not work.

**Comment by justbur** [comment]
Check the first line of the readme. This package was merged with evil-collection

**Comment by janmasrovira** [comment]
I missinterpreted what it is meant by *unmaintained* in the readme. I thought that it was meant that no updates were coming but you could still use this library.

**Comment by justbur** [comment]
Technically you can but it will conflict with evil-collection which is also on melpa. There was another issue about this so I decided to remove it from melpa as well.

**Comment by janmasrovira** [comment]
It makes sense. 
I'm affected by this since I use the git layer of spacemacs, which has not been updated to use evil-collection yet.
Thus I imagine that a non-negligible amount of people will face this issue as well. I thinkg it would be worth to explicitely mention on the readme that this package is no longer in Melpa.

**Comment by justbur** [comment]
Sure I can do that. I submitted the PR to have it removed a little while ago but had no control over when it actually happened.

**Comment by SimonAM** [comment]
For spacemacs users, go into your .emacs.d and pull latest spacemacs version to get an updated git-layer, thus avoiding errors related to yout git-layer referring to evil-magit.
